version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: email-marketing-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/data/email-marketing.db
      - JWT_SECRET=${JWT_SECRET:-change-this-to-a-secure-random-string}
      - JWT_EXPIRES_IN=7d
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme123}
      - SMTP_HOST=smtp-relay.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_FROM_EMAIL=info@myndsol.com
      - SMTP_FROM_NAME=Mynd Solution
      - APP_URL=https://marketing.myndsolution.com
      - FRONTEND_URL=https://marketing.myndsolution.com
      - TRACKING_DOMAIN=marketing.myndsolution.com
      - DKIM_DOMAIN=myndsolution.com
      - DKIM_SELECTOR=default
      - DKIM_PRIVATE_KEY_PATH=/app/config/dkim/private.key
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      - ./backend/config:/app/config
    restart: unless-stopped
    networks:
      - email-marketing-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email-marketing-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - email-marketing-network

  nginx:
    image: nginx:alpine
    container_name: email-marketing-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - email-marketing-network

networks:
  email-marketing-network:
    driver: bridge

volumes:
  backend-data:
  backend-logs:
